version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
  settings:
    copyloopvar:
      check-alias: true
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/nickbryan/slogutil
            - github.com/google/go-cmp/cmp
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    funlen:
      ignore-comments: true
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    grouper:
      const-require-grouping: true
      import-require-grouping: true
    interfacebloat:
      max: 3
    ireturn:
      allow:
        - anon
        - error
        - empty
        - generic
        - stdlib
    misspell:
      locale: US
    nestif:
      min-complexity: 7
    nilnil:
      detect-opposite: true
    nlreturn:
      block-size: 2
    nolintlint:
      require-explanation: true
      require-specific: true
    sloglint:
      attr-only: true
      no-global: all
      context: all
      static-msg: true
      key-naming-case: snake
      forbidden-keys:
        - time
        - level
        - msg
        - source
    tagalign:
      order:
        - json
        - query
        - path
        - header
        - default
        - validate
    usestdlibvars:
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
    usetesting:
      os-temp-dir: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - gochecknoglobals
          - containedctx
          - cyclop
          - err113
          - exhaustruct
          - funlen
          - gocognit
          - gocyclo
          - maintidx
          - nestif
          - nilnil
          - wrapcheck
        path: _test\.go
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/nickbryan
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
